export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUESTS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_DETAILS";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_DETAILS_FAILURE = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS";
